[package]
name = "chocopy-rs"
version = "0.1.0"
authors = ["Weiyi Wang <wwylele@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.7"
enum_dispatch = "0.3"
getopts = "0.2"
gimli = "0.20"
object = { git = "https://github.com/gimli-rs/object", features = ["write"] }
cc = "1.0"
once_cell = "1.3"
md-5 = "0.8"
