[package]
name = "chocopy-rs"
version = "0.1.0"
authors = ["Weiyi Wang <wwylele@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-std = "1.5"
faerie = "0.14"
target-lexicon = "0.10"
rand = "0.7"
